In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df=pd.read_csv("retail_product_demand.csv")
print(df.head())
print(df.shape)
print(df.columns)

features=["Price","Promotion","Advertising"]
y=df["Demand"]
print(y.head())
X=df[features]
print(X.head())

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

     Month  Price  Promotion  Advertising  Demand
0  2023-01  28.90          1       672.30     144
1  2023-02  19.85          1       404.68     154
2  2023-03  31.18          0       923.63     136
3  2023-04  26.83          0       543.86      90
4  2023-05  10.54          0       150.48     130
(240, 5)
Index(['Month', 'Price', 'Promotion', 'Advertising', 'Demand'], dtype='object')
0    144
1    154
2    136
3     90
4    130
Name: Demand, dtype: int64
   Price  Promotion  Advertising
0  28.90          1       672.30
1  19.85          1       404.68
2  31.18          0       923.63
3  26.83          0       543.86
4  10.54          0       150.48

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

linear_model=LinearRegression()
linear_model.fit(X_train,y_train)
linear_pred=linear_model.predict(X_test)

dt=DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
dt_pred=dt.predict(X_test)

rf=RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_pred=rf.predict(X_test)

knn=KNeighborsRegressor()
knn.fit(X_train, y_train)
knn_pred=knn.predict(X_test)

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import math

metrics=pd.DataFrame()
metrics["Model"]=["Linear Regression", "Decision Tree", "Random Forest", "KNN"]
metrics["MAE"]=[mean_absolute_error(y_test, linear_pred), 
                mean_absolute_error(y_test, dt_pred),
                mean_absolute_error(y_test, rf_pred),
                mean_absolute_error(y_test, knn_pred)]
metrics["MSE"]=[mean_squared_error(y_test,dt_pred),
                mean_squared_error(y_test,dt_pred),
                mean_squared_error(y_test,rf_pred),
                mean_squared_error(y_test, knn_pred)]
metrics["RMSE"]=[math.sqrt(mean_squared_error(y_test,dt_pred)),
                math.sqrt(mean_squared_error(y_test,dt_pred)),
                math.sqrt(mean_squared_error(y_test,rf_pred)),
                math.sqrt(mean_squared_error(y_test, knn_pred))]
metrics["R-squared"]=[r2_score(y_test,dt_pred),
                r2_score(y_test,dt_pred),
                r2_score(y_test,rf_pred),
                r2_score(y_test, knn_pred)]

metrics.set_index("Model")

                         MAE         MSE       RMSE  R-squared
Model
Linear Regression  14.840507  698.000000  26.419690   0.562186
Decision Tree      22.666667  698.000000  26.419690   0.562186
Random Forest      17.022500  422.361725  20.551441   0.735078
KNN                26.608333  992.073333  31.497196   0.377731

In [34]:
linear_pred_copy=linear_pred
linear_pred_copy[4]=1000
linear_pred

metrics_copy=pd.DataFrame()
metrics_copy["Model"]=["Linear Regression", "Decision Tree", "Random Forest", "KNN"]
metrics_copy["MAE"]=[mean_absolute_error(y_test, linear_pred), 
                mean_absolute_error(y_test, dt_pred),
                mean_absolute_error(y_test, rf_pred),
                mean_absolute_error(y_test, knn_pred)]
metrics_copy["MSE"]=[mean_squared_error(y_test,dt_pred),
                mean_squared_error(y_test,dt_pred),
                mean_squared_error(y_test,rf_pred),
                mean_squared_error(y_test, knn_pred)]
metrics_copy["RMSE"]=[math.sqrt(mean_squared_error(y_test,dt_pred)),
                math.sqrt(mean_squared_error(y_test,dt_pred)),
                math.sqrt(mean_squared_error(y_test,rf_pred)),
                math.sqrt(mean_squared_error(y_test, knn_pred))]
metrics_copy["R-squared"]=[r2_score(y_test,dt_pred),
                r2_score(y_test,dt_pred),
                r2_score(y_test,rf_pred),
                r2_score(y_test, knn_pred)]

metrics_copy.set_index("Model")

                         MAE         MSE       RMSE  R-squared
Model
Linear Regression  31.681219  698.000000  26.419690   0.562186
Decision Tree      22.666667  698.000000  26.419690   0.562186
Random Forest      17.022500  422.361725  20.551441   0.735078
KNN                26.608333  992.073333  31.497196   0.377731